import test from 'node:test';
import assert from 'node:assert/strict';
import {cents,payment,remaining,status,settleInvoice,canApprove,csvCell} from '../core.mjs';
import * as core from '../core.mjs';
const invoice={amount_minor:10000,paid_minor:2000,due_date:'2026-09-01',followup_state:'approved'};
test('money conversion is exact and rejects invalid input',()=>{assert.equal(cents('0.29'),29);assert.equal(cents('1234.56'),123456);for(const x of ['1.001','-3','Infinity','1e4','0'])assert.throws(()=>cents(x));});
test('partial payment keeps balance and full payment cancels follow-up',()=>{const partial=payment(invoice,3000);assert.equal(remaining(partial),5000);assert.equal(partial.followup_state,'approved');const full=payment(partial,5000);assert.equal(status(full),'Paid');assert.equal(full.followup_state,'cancelled');assert.equal(canApprove(full),false);assert.throws(()=>payment(full,1));});
test('already-paid settlement clears reminder scheduling for both invoice schemas',()=>{assert.deepEqual(settleInvoice({invoice:{amount_minor:1000,paid_minor:0,followup_state:'approved',next_follow_up_at:'2026-09-24T09:00:00Z'},alreadyPaid:true}),{amount_minor:1000,paid_minor:1000,followup_state:'cancelled',next_follow_up_at:null,status:'paid'});const row=settleInvoice({invoice:{total_amount:10,amount_paid:0,status:'draft',metadata:{followup_state:'approved'}},alreadyPaid:true});assert.equal(row.amount_paid,10);assert.equal(row.status,'paid');assert.equal(row.metadata.followup_state,'cancelled');assert.equal(row.metadata.next_follow_up_at,null);});
test('void and cancelled invoices cannot accept payment or follow-up approval',()=>{for(const terminal of ['void','cancelled']){const row={amount_minor:10000,paid_minor:0,due_date:'2026-10-01',status:terminal,followup_state:'draft'};assert.throws(()=>payment(row,1),/terminal|void|cancelled/i);assert.equal(canApprove(row),false);assert.equal(status(row),terminal==='void'?'Void':'Cancelled')}});
test('an ambiguous already-paid RPC retry reuses the saved invoice and idempotency key',async()=>{assert.equal(typeof core.saveAndSettleInvoice,'function');const state={},calls=[];let saves=0,loseFirstResponse=true;const saveInvoice=async()=>{saves++;return{id:'saved-invoice',updated_at:'invoice-version-2'}};const recordPayment=async request=>{calls.push(request);if(loseFirstResponse){loseFirstResponse=false;throw Error('RPC response was lost after commit')}return{settled:true}};const settle=()=>core.saveAndSettleInvoice({state,saveInvoice,recordPayment});await assert.rejects(settle(),/response was lost/);assert.equal(state.invoiceId,'saved-invoice');assert.equal(state.invoiceUpdatedAt,'invoice-version-2');const result=await settle();assert.deepEqual(result,{settled:true});assert.equal(saves,1);assert.equal(calls.length,2);assert.deepEqual(calls[1],calls[0]);assert.ok(calls[0].idempotencyKey)});
test('a payment form cannot reuse its request key after changing amount or reference',()=>{assert.equal(typeof core.paymentRequestKey,'function');const state={};const key=core.paymentRequestKey(state,{amount:10,reference:'receipt 1'});assert.equal(core.paymentRequestKey(state,{amount:10,reference:'receipt 1'}),key);assert.throws(()=>core.paymentRequestKey(state,{amount:11,reference:'receipt 1'}),/pending.*same amount and reference/i);assert.throws(()=>core.paymentRequestKey(state,{amount:10,reference:'receipt 2'}),/pending.*same amount and reference/i)});
test('overpayments and malformed payment amounts are rejected',()=>{for(const x of [8001,0,-1,1.5,NaN])assert.throws(()=>payment(invoice,x));});
test('due dates use date-only comparison',()=>{assert.equal(status(invoice,'2026-09-01'),'Due today');assert.equal(status(invoice,'2026-09-02'),'Overdue');assert.equal(status(invoice,'2026-08-31'),'Open');});
test('CSV export quotes values and neutralizes spreadsheet formulas',()=>{assert.equal(csvCell('=IMPORTXML("x")'),'"\'=IMPORTXML(""x"")"');assert.equal(csvCell('A, B'),'"A, B"');});

