import test from 'node:test';
import assert from 'node:assert/strict';
import {createAutomationRuntime} from '../automation/runtime.mjs';
import {MemoryAutomationStore, SupabaseAutomationStore} from '../automation/store.mjs';
import {MockWhatsAppProvider} from '../automation/whatsapp/mock.mjs';
const now=new Date('2026-09-22T10:00:00Z'),scope={ownerId:'o',workspaceId:'w',invoiceId:'i'};
function setup(extra={}){const store=new MemoryAutomationStore({now:()=>now});store.seedInvoice({id:'i',...scope,amountMinor:1000,paidMinor:0,followupState:'approved',nextFollowUpAt:'2026-09-22T09:00:00Z',customerPhone:'+919876543210',...extra});store.scopeQuery=()=>({});store.request=async()=>[{id:'i'}];const runtime=createAutomationRuntime({store,provider:new MockWhatsAppProvider(),env:{WHATSAPP_PROVIDER:'mock',NODE_ENV:'test'},clock:()=>now});return {store,runtime};}
test('configure, pause, resume and scheduled tick work together',async()=>{const {store,runtime}=setup();await runtime.configure(scope,{customerPhone:'+919876543210',timezone:'UTC',first_reminder_days:0});await runtime.pause(scope);assert.equal(store.getInvoice(scope).nextFollowUpAt,null);await runtime.resume(scope);assert.equal((await runtime.tick(scope)).results[0].status,'sent');});
test('invalid cadence and paid resume are rejected',async()=>{const {runtime}=setup({paidMinor:1000});await assert.rejects(runtime.resume(scope),/Paid invoices/);await assert.rejects(runtime.configure(scope,{customerPhone:'+919876543210',hoursStart:'18:00',hoursEnd:'09:00'}),/Contact hours/);});
test('linked accounting paid balance prevents runtime outbound',async()=>{const {store}=setup({currency:'INR',bookkeeping_provider:'zoho',bookkeeping_record_id:'external-1'});let calls=0;const runtime=createAutomationRuntime({store,env:{WHATSAPP_PROVIDER:'mock',NODE_ENV:'test'},provider:{async sendReminder(){calls++;}},clock:()=>now,accounting:{async latestInvoiceBalance(input){assert.equal(input.invoiceId,'external-1');return {currency:'INR',amountMinor:1000,balanceMinor:0};}}});assert.equal((await runtime.tick(scope)).results[0].reason,'paid');assert.equal(calls,0);});
test('currency mismatch blocks runtime reminder',async()=>{const {store}=setup({currency:'INR',bookkeeping_provider:'quickbooks',bookkeeping_record_id:'external-1'});let calls=0;const runtime=createAutomationRuntime({store,env:{WHATSAPP_PROVIDER:'mock',NODE_ENV:'test'},provider:{async sendReminder(){calls++;}},clock:()=>now,accounting:{async latestInvoiceBalance(){return {currency:'USD',amountMinor:1000,balanceMinor:1000};}}});assert.equal((await runtime.tick(scope)).results[0].status,'quarantined');assert.equal(calls,0);});
test('Supabase adapter preserves SQL claim IDs and explicit null scheduling',async()=>{const requests=[];const store=new SupabaseAutomationStore({url:'https://db.test',key:'test',fetchImpl:async(url,options)=>{requests.push({url:String(url),body:JSON.parse(options.body)});return new Response(JSON.stringify(String(url).includes('/rpc/')?[{claim_id:'claim',invoice_id:'i',invoice_version:2}]:[{id:'i'}]));}});assert.equal((await store.claimDueFollowups(scope))[0].id,'claim');await store.updateInvoice({...scope,expectedVersion:2,nextFollowUpAt:null,reminderCount:1});assert.equal(requests[1].body.next_follow_up_at,null);assert.equal(requests[1].body.reminder_count,1);assert.match(requests[1].url,/automation_version=eq.2/);});
